### ISSUE TITLE
Which Bot?

### ISSUE THREAD

**Issue by pukker87** [DuckTeamOfficial/BadgeScraper#9]
Hello,

I wanna ask you if this work with the bot from Blu?

Do you have maybe a video tutorial for a newbienoob like me? I added you in steam.

regards

**Comment by DuckTeamOfficial** [comment]
I know this works for Tims bot, I'm unsure if It is used by Blu's bot, if I had access to code, then I could tell you if it is or not, and perhaps work a solution if it isn't.

**Comment by Buyachaka** [comment]
This works with all bots, just need to code it right. Its just a badge
scrapper then you can do anything with the info, like feeding it to blu's

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by pukker87** [comment]
ok, I have tested it and it works really good. Thanks you very much :D
